---

version: "3.0"

services:
  newspaper:
    build: 
      context: ./
    container_name: newspaper
    ports:
      - "5555:5000"
    environment:
      - LOG_LEVEL=DEBUG
      - ARTICLE_AMOUNT=25

